"""Add inventory event tables: acquisition, consumption, waste

Revision ID: 2e33d848de71
Revises: 7e088400ecec
Create Date: 2026-09-03 15:02:22.934256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e33d848de71'
down_revision: Union[str, Sequence[str], None] = '7e088400ecec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ingredient_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('unit', sa.String(length=40), nullable=False),
        sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'),
        sa.Column('acquired_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('quantity > 0', name='ck_acquisition_quantity_positive'),
        sa.CheckConstraint('cost >= 0', name='ck_acquisition_cost_nonnegative'),
        sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_acquisition_ingredient_id', 'acquisition', ['ingredient_id'], unique=False)

    op.create_table('consumption',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ingredient_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('unit', sa.String(length=40), nullable=False),
        sa.Column('consumed_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('quantity > 0', name='ck_consumption_quantity_positive'),
        sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consumption_ingredient_id', 'consumption', ['ingredient_id'], unique=False)

    op.create_table('waste',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ingredient_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('unit', sa.String(length=40), nullable=False),
        sa.Column('wasted_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('quantity > 0', name='ck_waste_quantity_positive'),
        sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waste_ingredient_id', 'waste', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waste_ingredient_id', table_name='waste')
    op.drop_table('waste')
    op.drop_index('ix_consumption_ingredient_id', table_name='consumption')
    op.drop_table('consumption')
    op.drop_index('ix_acquisition_ingredient_id', table_name='acquisition')
    op.drop_table('acquisition')
    # ### end Alembic commands ###